version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  # Dependabot only updates hashicorp GHAs, external GHAs are managed by internal tooling (tsccr)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "hashicorp/*"
