on:
  issues:
    types: [closed, deleted, reopened]
  pull_request_target:
    types: [closed, reopened]

name: Jira Sync

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Jira sync
    steps:

    - name: Login
      uses: atlassian/gajira-login@ca13f8850ea309cf44a6e4e0c49d9aa48ac3ca4c # v3
      if: contains(github.event.pull_request.labels.*.name, 'tf-devex-triage') || contains(github.event.issue.labels.*.name, 'tf-devex-triage')
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Search for existing issue
      id: search
      if: contains(github.event.pull_request.labels.*.name, 'tf-devex-triage') || contains(github.event.issue.labels.*.name, 'tf-devex-triage')
      uses: tomhjp/gh-action-jira-search@04700b457f317c3e341ce90da5a3ff4ce058f2fa # v0.2.2
      with:
        jql: 'project="TFECO" and "Team (R&D)[Labels]"="TF-DevEx" and description ~ "${{ github.event.issue.html_url || github.event.pull_request.html_url }}" and labels in (Github)'
    - name: Close task
      if: ( github.event.action == 'closed' || github.event.action == 'deleted' ) && steps.search.outputs.issue
      uses: atlassian/gajira-transition@4749176faf14633954d72af7a44d7f2af01cc92b # v3
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: "Closed"
    - name: Reopen task
      if: github.event.action == 'reopened' && steps.search.outputs.issue
      uses: atlassian/gajira-transition@4749176faf14633954d72af7a44d7f2af01cc92b # v3
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: "To Do"
